stages:
  - test
  - build
  - push
  - deploy

# ใส่ tags ให้ทุก job เพื่อบังคับให้มาวิ่งที่ Ubuntu เครื่องคุณ
default:
  tags:
    - informatics

test_backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test -- --watchAll=false

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test -- --watchAll=false

build_images:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest ./backend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest ./frontend

push_images:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest