sonar.projectKey=Pathamapo_fullstack-notesapp
sonar.organization=pathamapornw

sonar.projectName=fullstack-notesapp
sonar.projectVersion=1.0

sonar.sources=frontend,backend
sonar.sourceEncoding=UTF-8
